[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace_program = "Hnf7nuJLhXP5pMh7AQrqratPUWcAXzsw6MUf6vacY23V"

[programs.devnet]
marketplace_program = "Hnf7nuJLhXP5pMh7AQrqratPUWcAXzsw6MUf6vacY23V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nikhilkr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
